#!/bin/bash

# LICENSE UPL 1.0
#
# Copyright (c) 2020,2021 Oracle and/or its affiliates.
#
# Since: January, 2020
# Author: sanjay.singh@oracle.com, paramdeep.saini@oracle.com

TIMESTAMP=`date "+%Y-%m-%d"`
LOGFILE="/tmp/sharding_cmd_${TIMESTAMP}.log"

echo $(date -u) " : " $@ >> $LOGFILE 

cmd=$@

$cmd

if [ $? -eq 0 ]; then
  exit 0
else
  exit 127
fi
