---
# Copyright 2020, Oracle Corporation and/or affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl
# MAINTAINER <paramdeep.saini@oracle.com>
apiVersion: v1
kind: Secret
metadata:
 name: mysecret
type: Opaque
data:
  username: T1JBQ0xFX1BXRAo=
  password: T3JhY2xlXzE5Ywo=
