/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class oracle_sharding_tools_OCIDirectPath */

#ifndef _Included_oracle_sharding_tools_OCIDirectPath
#define _Included_oracle_sharding_tools_OCIDirectPath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     oracle_sharding_tools_OCIDirectPath
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_oracle_sharding_tools_OCIDirectPath_initialize
  (JNIEnv *, jclass);

/*
 * Class:     oracle_sharding_tools_OCIDirectPath
 * Method:    createInternal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_oracle_sharding_tools_OCIDirectPath_createInternal
  (JNIEnv *, jobject);

/*
 * Class:     oracle_sharding_tools_OCIDirectPath
 * Method:    connectInternal
 * Signature: (Ljava/lang/String;Ljava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_oracle_sharding_tools_OCIDirectPath_connectInternal
  (JNIEnv *, jobject, jstring, jstring, jbyteArray);

/*
 * Class:     oracle_sharding_tools_OCIDirectPath
 * Method:    closeInternal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_oracle_sharding_tools_OCIDirectPath_closeInternal
  (JNIEnv *, jobject);

/*
 * Class:     oracle_sharding_tools_OCIDirectPath
 * Method:    setTarget
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_oracle_sharding_tools_OCIDirectPath_setTarget
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     oracle_sharding_tools_OCIDirectPath
 * Method:    setData
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_oracle_sharding_tools_OCIDirectPath_setData
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     oracle_sharding_tools_OCIDirectPath
 * Method:    setValue
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_oracle_sharding_tools_OCIDirectPath_setValue__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     oracle_sharding_tools_OCIDirectPath
 * Method:    setValue
 * Signature: (I[BII)V
 */
JNIEXPORT void JNICALL Java_oracle_sharding_tools_OCIDirectPath_setValue__I_3BII
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     oracle_sharding_tools_OCIDirectPath
 * Method:    setValue
 * Signature: (I[B)V
 */
JNIEXPORT void JNICALL Java_oracle_sharding_tools_OCIDirectPath_setValue__I_3B
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     oracle_sharding_tools_OCIDirectPath
 * Method:    nextRow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_oracle_sharding_tools_OCIDirectPath_nextRow
  (JNIEnv *, jobject);

/*
 * Class:     oracle_sharding_tools_OCIDirectPath
 * Method:    addColumnDefinition
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_oracle_sharding_tools_OCIDirectPath_addColumnDefinition
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     oracle_sharding_tools_OCIDirectPath
 * Method:    reopen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_oracle_sharding_tools_OCIDirectPath_reopen
  (JNIEnv *, jobject);

/*
 * Class:     oracle_sharding_tools_OCIDirectPath
 * Method:    finish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_oracle_sharding_tools_OCIDirectPath_finish
  (JNIEnv *, jobject);

/*
 * Class:     oracle_sharding_tools_OCIDirectPath
 * Method:    discard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_oracle_sharding_tools_OCIDirectPath_discard
  (JNIEnv *, jobject);

/*
 * Class:     oracle_sharding_tools_OCIDirectPath
 * Method:    begin
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_oracle_sharding_tools_OCIDirectPath_begin
  (JNIEnv *, jobject);

/*
 * Class:     oracle_sharding_tools_OCIDirectPath
 * Method:    setAttribute
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_oracle_sharding_tools_OCIDirectPath_setAttribute
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
